[program:hr]
directory=/home/hr_telegram/
command=gunicorn --bind 0.0.0.0:443 wsgi:app
user=root
autostart=true
autorestart=true
process_name=helpresource
stdout_logfile=/home/hr_telegram/hr_std.log
stderr_logfile=/home/hr_telegram/hr_std.log
