[program:hr_bot]
directory=/home/hr_telegram/
command=python3 main.py
user=root
autostart=true
autorestart=true
process_name=hr_bot
stdout_logfile=/home/hr_telegram/hr_bot_std.log
stderr_logfile=/home/hr_telegram/hr_bot_std.log